### ISSUE TITLE
Send to anyone received amount slightly less than expected

### ISSUE THREAD

**Issue by Mattybuoy** [WillyTheCat/BitCash#5]
I did a test by sending 1 BITC from my QT wallet to "anyone" and then receiving it in the web wallet. The tx fee was paid by the sending QT wallet.

The actual amount which ended up in the web wallet was 0.999988241 (note 9 decimal places rather than usual 8).

TX ID is  815e30a36d2753ca249a8b1ab2b462f8b06df410fd6fa9396bb50131d1bb4a6a

**Comment by WillyTheCat** [comment]
This is normal. There are two transactions. One to the link and one from the link.
